version: '3.8'
services:
  sig_intelbras:
    container_name: sig-capacita 
    ports:
      - '2000:22'
      - '8080-8081:8080-8081'
    volumes:
      - ./database:/var/lib/pgsql/data
      - ./logs/:/usr/bin/imn/logs/
    build:
      context: .
      dockerfile: Dockerfile

