# Main composition file for SIG Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore
# Capacitação Redes - PV Intelbras

version: '3.8'
services:
  sig_intelbras:
    container_name: sig-capacita-v2
    # Map container ports 8080 and 8081.
    ports:
      - '8080-8081:8080-8081'
    # Mount local directories as volumes inside the container:
    volumes:
      - "./app/config/log.properties:/usr/bin/imn/config/log.properties"
      - "./app/config/app.constant_base.js:/usr/bin/imn/BOOT-INF/classes/static/app/app.constant_base.js"
      - "./app/config/app.constant_base.js:/project/BOOT-INF/classes/static/app/app.constant_base.js"
      - "./app/imn-core.jar:/project/imn-core.jar"
      - "./app/imn-webapp.jar:/project/imn-webapp.jar"
      - "./logs:/project/logs"
      - sigdb:/var/lib/postgresql/9.5/main
    build:
      context: .
      dockerfile: ./docker/Dockerfile

# Define Docker volumes to mount database files:
volumes:
  sigdb:
